name: k8s image sync
on: push
jobs:
  dockerLogin:
    name: docker login
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: docker login
      uses: actions/docker/login@master
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: sync
      uses: maguowei/actions/k8s-image-sync@master
      env:
        KUBERNETES_VERSION: v1.14.3
        REGISTRY: gotok8s
